export const SAVE_MOBILE_NUMBER='SAVE_MOBILE_NUMBER'

export const ROOM_NUMBER_SAVE='ROOM_NUMBER_SAVE'

export const ROOM_NAME_SAVE='ROOM_NAME_SAVE'

export const SWITCHBOARD_NUMBER='SWITCHBOARD_NUMBER'

export const APPLIANCE_SAVE='APPLIANCE_SAVE'

